language: python

dist: bionic
sudo: required

git:
  depth: 1000

matrix:
  fast_finish: true
  include:
  - python: 3.7

before_install:
  - pip install pip --upgrade

install:
  - pip install -e .

script:
  - cd docs
  - pip install -r requirements.txt
  - make html

after_success:
  - |
    if [[ -z ${TRAVIS_TAG} ]]; then
      echo "Not a tagged build."
    else
      pip install doctr
      doctr deploy . --build-tags
    fi
